version: "2"

volumes:
  prometheus:
  bindplane:

services:
  prometheus:
    container_name: prometheus
    restart: always
    image: prom/prometheus:v2.47.2
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=2d'
      - '--web.enable-remote-write-receiver'
      - '--web.listen-address=0.0.0.0:9090'
      - '--storage.tsdb.path=/prometheus/tsdb'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/rules.yml:/etc/prometheus/rules.yml
      - prometheus:/prometheus:rw

  transform:
    container_name: transform-agent
    restart: always
    image: ghcr.io/observiq/bindplane-transform-agent:latest

  bindplane:
    container_name: bindplane
    restart: always
    image: ghcr.io/observiq/bindplane-ee:1.42.0
    ports:
      - 3001:3001
    environment:
      - BINDPLANE_REMOTE_URL=http://bindplane:3001
      - BINDPLANE_SESSIONS_SECRET=403dd8ff-72a9-4401-9a66-e54b37d6e0ce
      - BINDPLANE_LOG_OUTPUT=stdout
      - BINDPLANE_ACCEPT_EULA=true
      - BINDPLANE_SECRET_KEY=403dd8ff-72a9-4401-9a66-e54b37d6e0ce
      - BINDPLANE_TRANSFORM_AGENT_ENABLE_REMOTE=true
      - BINDPLANE_TRANSFORM_AGENT_REMOTE_AGENTS=transform:4568
      - BINDPLANE_PROMETHEUS_ENABLE_REMOTE=true
      - BINDPLANE_PROMETHEUS_HOST=prometheus
      - BINDPLANE_PROMETHEUS_PORT=9090
      - BINDPLANE_STORE_TYPE=bbolt
      - BINDPLANE_STORE_BBOLT_PATH=/data/bindplane.db:rw
    volumes:
      - bindplane:/data
    depends_on:
      - prometheus
      - transform

  agent:
    deploy:
      replicas: 1
    image: observiq/bindplane-agent:1.43.0
    environment:
      - OPAMP_ENDPOINT=ws://bindplane:3001/v1/opamp
      - OPAMP_SECRET_KEY=403dd8ff-72a9-4401-9a66-e54b37d6e0ce
      - OPAMP_LABELS=configuration=test
    restart: always
